/**
 * Per-team-count round-robin patterns for prelim quizzes, transcribed
 * verbatim from `docs/rules.md` §"Preliminary Round Brackets". Each
 * value is a list of N quizzes (where N = team count); each quiz is
 * exactly 3 letters drawn from A through the Nth letter, and every
 * letter appears in exactly 3 quizzes (each team plays 3 prelims).
 *
 * The rule-book table is the canonical source; consumers (Populate)
 * should not generate their own patterns.
 */
export const PRELIM_DRAW_PATTERNS: Record<
  number,
  ReadonlyArray<readonly [string, string, string]>
> = {
  4: [
    ['A', 'B', 'C'],
    ['D', 'A', 'B'],
    ['C', 'D', 'A'],
    ['B', 'C', 'D'],
  ],
  5: [
    ['A', 'B', 'C'],
    ['D', 'E', 'A'],
    ['B', 'C', 'D'],
    ['E', 'A', 'B'],
    ['C', 'D', 'E'],
  ],
  6: [
    ['A', 'C', 'F'],
    ['B', 'D', 'A'],
    ['C', 'E', 'B'],
    ['D', 'F', 'C'],
    ['E', 'A', 'D'],
    ['F', 'B', 'E'],
  ],
  7: [
    ['A', 'C', 'G'],
    ['B', 'D', 'A'],
    ['C', 'E', 'B'],
    ['D', 'F', 'C'],
    ['E', 'G', 'D'],
    ['F', 'A', 'E'],
    ['G', 'B', 'F'],
  ],
  8: [
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'A'],
    ['G', 'C', 'E'],
    ['A', 'D', 'F'],
    ['B', 'E', 'H'],
    ['F', 'H', 'C'],
    ['G', 'B', 'D'],
  ],
  9: [
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I'],
    ['A', 'D', 'G'],
    ['B', 'E', 'H'],
    ['C', 'D', 'H'],
    ['A', 'E', 'I'],
    ['B', 'F', 'G'],
    ['C', 'F', 'I'],
  ],
  10: [
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I'],
    ['J', 'B', 'F'],
    ['A', 'D', 'G'],
    ['B', 'E', 'H'],
    ['C', 'F', 'I'],
    ['J', 'E', 'G'],
    ['C', 'D', 'H'],
    ['I', 'J', 'A'],
  ],
  11: [
    ['A', 'B', 'J'],
    ['B', 'C', 'K'],
    ['C', 'D', 'A'],
    ['D', 'E', 'B'],
    ['E', 'F', 'C'],
    ['F', 'G', 'D'],
    ['G', 'H', 'E'],
    ['H', 'I', 'F'],
    ['I', 'J', 'G'],
    ['J', 'K', 'H'],
    ['K', 'A', 'I'],
  ],
  12: [
    ['A', 'B', 'K'],
    ['C', 'F', 'E'],
    ['G', 'I', 'J'],
    ['E', 'D', 'B'],
    ['F', 'H', 'I'],
    ['A', 'J', 'L'],
    ['E', 'G', 'H'],
    ['A', 'C', 'D'],
    ['K', 'J', 'H'],
    ['L', 'C', 'B'],
    ['D', 'F', 'G'],
    ['I', 'L', 'K'],
  ],
  13: [
    ['C', 'F', 'G'],
    ['I', 'H', 'E'],
    ['G', 'J', 'K'],
    ['L', 'I', 'M'],
    ['B', 'K', 'A'],
    ['D', 'M', 'C'],
    ['B', 'E', 'F'],
    ['H', 'G', 'D'],
    ['F', 'J', 'I'],
    ['K', 'L', 'H'],
    ['A', 'J', 'M'],
    ['C', 'B', 'L'],
    ['D', 'A', 'E'],
  ],
  14: [
    ['A', 'D', 'E'],
    ['C', 'F', 'G'],
    ['E', 'H', 'I'],
    ['I', 'L', 'M'],
    ['G', 'J', 'K'],
    ['K', 'N', 'A'],
    ['B', 'M', 'C'],
    ['L', 'K', 'H'],
    ['F', 'I', 'J'],
    ['D', 'H', 'G'],
    ['B', 'E', 'F'],
    ['J', 'M', 'N'],
    ['A', 'B', 'L'],
    ['N', 'C', 'D'],
  ],
  15: [
    ['B', 'E', 'F'],
    ['G', 'J', 'K'],
    ['E', 'D', 'A'],
    ['D', 'C', 'O'],
    ['N', 'B', 'C'],
    ['A', 'L', 'O'],
    ['C', 'F', 'G'],
    ['F', 'I', 'J'],
    ['I', 'M', 'L'],
    ['H', 'G', 'D'],
    ['M', 'J', 'N'],
    ['L', 'K', 'H'],
    ['A', 'B', 'M'],
    ['I', 'H', 'E'],
    ['O', 'N', 'K'],
  ],
  16: [
    ['C', 'F', 'G'],
    ['A', 'D', 'E'],
    ['D', 'G', 'H'],
    ['L', 'O', 'P'],
    ['E', 'B', 'F'],
    ['K', 'O', 'N'],
    ['P', 'D', 'C'],
    ['H', 'E', 'I'],
    ['H', 'K', 'L'],
    ['B', 'C', 'O'],
    ['F', 'I', 'J'],
    ['N', 'A', 'B'],
    ['I', 'L', 'M'],
    ['G', 'J', 'K'],
    ['J', 'M', 'N'],
    ['M', 'P', 'A'],
  ],
  17: [
    ['C', 'D', 'L'],
    ['E', 'G', 'O'],
    ['H', 'F', 'M'],
    ['K', 'I', 'P'],
    ['N', 'J', 'Q'],
    ['F', 'A', 'L'],
    ['B', 'M', 'G'],
    ['D', 'O', 'I'],
    ['H', 'C', 'N'],
    ['E', 'K', 'Q'],
    ['J', 'P', 'B'],
    ['M', 'N', 'O'],
    ['D', 'E', 'F'],
    ['A', 'B', 'C'],
    ['G', 'H', 'I'],
    ['J', 'L', 'K'],
    ['P', 'Q', 'A'],
  ],
  18: [
    ['A', 'J', 'R'],
    ['B', 'P', 'K'],
    ['F', 'I', 'M'],
    ['D', 'G', 'N'],
    ['C', 'L', 'Q'],
    ['E', 'O', 'H'],
    ['G', 'M', 'A'],
    ['J', 'D', 'P'],
    ['H', 'B', 'N'],
    ['I', 'C', 'O'],
    ['K', 'E', 'Q'],
    ['L', 'R', 'F'],
    ['B', 'A', 'C'],
    ['D', 'F', 'E'],
    ['G', 'H', 'I'],
    ['J', 'K', 'L'],
    ['M', 'N', 'O'],
    ['P', 'Q', 'R'],
  ],
  19: [
    ['I', 'O', 'S'],
    ['H', 'F', 'N'],
    ['L', 'C', 'P'],
    ['E', 'G', 'M'],
    ['A', 'J', 'Q'],
    ['K', 'R', 'D'],
    ['C', 'I', 'N'],
    ['B', 'M', 'H'],
    ['F', 'L', 'Q'],
    ['J', 'D', 'O'],
    ['E', 'P', 'K'],
    ['R', 'S', 'B'],
    ['G', 'H', 'I'],
    ['D', 'E', 'F'],
    ['A', 'B', 'C'],
    ['J', 'K', 'L'],
    ['M', 'N', 'O'],
    ['P', 'Q', 'R'],
    ['S', 'A', 'G'],
  ],
  20: [
    ['H', 'S', 'O'],
    ['T', 'G', 'P'],
    ['C', 'J', 'M'],
    ['N', 'F', 'Q'],
    ['B', 'I', 'R'],
    ['E', 'L', 'S'],
    ['K', 'D', 'T'],
    ['H', 'C', 'N'],
    ['J', 'P', 'B'],
    ['F', 'A', 'L'],
    ['D', 'O', 'I'],
    ['E', 'Q', 'K'],
    ['R', 'M', 'G'],
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I'],
    ['J', 'K', 'L'],
    ['M', 'N', 'O'],
    ['P', 'R', 'Q'],
    ['S', 'T', 'A'],
  ],
  21: [
    ['D', 'A', 'G'],
    ['J', 'M', 'P'],
    ['B', 'H', 'E'],
    ['K', 'N', 'Q'],
    ['L', 'R', 'O'],
    ['C', 'F', 'I'],
    ['S', 'P', 'A'],
    ['H', 'U', 'R'],
    ['T', 'L', 'Q'],
    ['M', 'D', 'I'],
    ['S', 'C', 'J'],
    ['F', 'K', 'U'],
    ['E', 'T', 'N'],
    ['O', 'G', 'B'],
    ['P', 'Q', 'R'],
    ['T', 'S', 'U'],
    ['D', 'E', 'F'],
    ['A', 'B', 'C'],
    ['G', 'I', 'H'],
    ['K', 'J', 'L'],
    ['M', 'O', 'N'],
  ],
}

/** Returns the rule-book draw for `teamCount`, or `null` if no pattern
 *  is published for that count (i.e. teamCount < 4 or > 21). */
export function getPrelimDraw(
  teamCount: number,
): ReadonlyArray<readonly [string, string, string]> | null {
  return PRELIM_DRAW_PATTERNS[teamCount] ?? null
}
