name = "qzr-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "qzr-db"
database_id = "d10523ed-a7bf-43d7-989f-2ab0c1f2ca1f"

[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://api.versevault.ca"
